### ISSUE TITLE
lmao pussies

### ISSUE THREAD

**Issue by Beard3dTurtle** [DamagingRose/Rose-Injector#107]
yall discontinued the project for "whitehat". "I wanna leave this life, what if somebody doxxed u or stole ur info" 🤓

Blud got so scared by his face reveal his ass turned from black hat to whitehat

**Comment by Gumbobrot** [comment]
No, I am just not a extremely disgusting person like you. Am I the one destroying innocent people's lifes and stealing their money? And even being proud of that? No pierro and I aren't, and that's why we quit for a time, because of disgusting people like you. Just leave us alone dude. You are the only p6ssy hiding behind a monitor and stealing people's data/money.

**Comment by Gumbobrot** [comment]
That's be the of DamagingRose for a specific time. hope you all can understand that, we don't want to be the reason why peoples data/money is being stolen. And after I heard what my community talk about and how they see the world and threat other people, I don't want to create projects or a community for/with these people anymore.

**Comment by xpierroz** [comment]
fr bro is scared to send his loc 😹😹‼️🔥 pussssies ‼️🗣️🔥😹
