### ISSUE TITLE
Rose devs, what is going on here?

### ISSUE THREAD

**Issue by neek8044** [DamagingRose/Rose-Injector#30]
A friend of mine found this repo and ran it. Now the webhook we had assigned sent back to our server their token and other sensitive info. Is this some kind of bug because it is not finished or was this on purpose? Because all they did was to just start main.py in the tools directory. I also saw where the base64 in configuration.py leads to, and seems like it is your webhook. Can you explain what is going on here?

**Comment by Gumbobrot** [comment]
Hey neek8044,

He needs to insert his webhook. If he didn't an error should have appeared. Don't worry, nothing came up on my webhook. I may also show you proofs on Discord: Gumbobrot#4888. It is maybe because the project is still under development and we left the debug_mode in config.json on true. There are just too many errors. And yes, that's what this project is supposed to do. It collects all your data and sends it to a Discord webhook, that's also what the title says. Sorry if we did a mistake. If you need any further assistance please contact me on Discord: Gumbobrot#4888. And you may also decode the base64 encoded values. They are only our HWID's and development webhook's (for debug mode). We just wanted to do this to hide our HWID's and development webhook's, because we don't wanna leak ourselves. By the way, the program is currently configured that it looks for a tools/config.json path. We will fix this soon. Just wanted to tell you that, so the program isn't really functional at the moment. :D

Best regards
Gumbobrot

**Comment by neek8044** [comment]
Thank you very much from both me and my friend! You can close this issue, or even delete it if you wish.

Again thanks for the help,
Nick

**Comment by Gumbobrot** [comment]
> Thanks for the reply,
> Yeah that actually makes sense. However, my friend deleted python and all the source files but when he logs back the webhook keeps sending the new token and other stuff. Would it be easy if you told me how do I disinfect them? I cannot find any solution.
> 
> PS: About the base64 webhook part, you might want to have the webhook on a server and download it in a temp file, read it, and then delete it to properly hide it from the public. 

Hey neek8044,

if you (or your friend) added me on Discord, I could show you an exact tutorial about how to remove injections, because it is pretty difficult and not just re-installing Discord.

Best regards
Gumbobrot

@neek8044

**Comment by neek8044** [comment]
Hi Gumbobrot,
I had given my friend your nametag to send you in case they needed help. I think they already reinstalled discord, but if there are more that have to be done I can tell them to message you.
\- Nick

**Comment by Gumbobrot** [comment]
> Hi Gumbobrot,
> I had given my friend your nametag to send you in case they needed help. I think they already reinstalled discord, but if there are more that have to be done I can tell them to message you.
> \- Nick

Hi neek8044,

just downloading the Discord Installer and opening it or deleting the Discord App from the Apps Tab doesn't fix anything. You can edit files to instantly remove the injection or delete the Discord files in %appdata% and %localappdata% and then run the Discord Installer. I would also suggest to check shell:startup and shell:common startup for malicious files. Just to be sure.

Best regards
Gumbobrot

**Comment by neek8044** [comment]
Thanks for the quick reply. We actually deleted discord from the control panel and then reinstalled it so I believe the AppData were also cleared. I will tell them to check startup and commons to make sure everything is alright.

You have been really helpful, thank you for everything!

**Comment by Gumbobrot** [comment]
No problem and thanks to you but when I tried it a few months ago, deleting from the control panel didn't dslete the appdata files. But it seems to be working for him, so nevermind.
